export const contacts = [
  {
    id: 1,
    firstName: 'Tushar',
    lastName: 'Dahule',
    email: 'tushardahule@gmail.com',
  },
  {
    id: 2,
    firstName: 'John',
    lastName: 'Wick',
    email: 'johnwick@gmail.com',
  },
  {
    id: 3,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 4,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 5,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 6,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 7,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 8,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 9,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 10,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 11,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 12,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 13,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 14,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 15,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 16,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 17,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
];
