export const contacts = [
  {
    id: 1,
    firstName: 'Tushar',
    lastName: 'Dahule',
    email: 'tushardahule@gmail.com',
  },
  {
    id: 2,
    firstName: 'John',
    lastName: 'Wick',
    email: 'johnwick@gmail.com',
  },
  {
    id: 3,
    firstName: 'Mat',
    lastName: 'Hardy',
    email: 'mathardy@gmail.com',
  },
  {
    id: 4,
    firstName: 'Matthew',
    lastName: 'Harddvy',
    email: 'mathardvy@gmail.com',
  },
  {
    id: 5,
    firstName: 'Matbb',
    lastName: 'Hardddy',
    email: 'mathaeerdy@gmail.com',
  },
  {
    id: 6,
    firstName: 'EfMat',
    lastName: 'Haddrdy',
    email: 'mathavvrdy@gmail.com',
  },
  {
    id: 7,
    firstName: 'WeewMat',
    lastName: 'WHardy',
    email: 'mdathardy@gmail.com',
  },
  {
    id: 8,
    firstName: 'GMat',
    lastName: 'GHardy',
    email: 'Gmathardy@gmail.com',
  },
  {
    id: 9,
    firstName: 'LMat',
    lastName: 'LHardy',
    email: 'lmathardy@gmail.com',
  },
  {
    id: 10,
    firstName: 'KMat',
    lastName: 'kHardy',
    email: 'klmathardy@gmail.com',
  },
  {
    id: 11,
    firstName: 'SMat',
    lastName: 'SHardy',
    email: 'smathardy@gmail.com',
  },
  {
    id: 12,
    firstName: 'MMat',
    lastName: 'MHardy',
    email: 'mmathardy@gmail.com',
  },
  {
    id: 13,
    firstName: 'QMat',
    lastName: 'QHardy',
    email: 'qmathardy@gmail.com',
  },
  {
    id: 14,
    firstName: 'XMat',
    lastName: 'XHardy',
    email: 'xmathardy@gmail.com',
  },
  {
    id: 15,
    firstName: 'BMat',
    lastName: 'BHardy',
    email: 'bmathardy@gmail.com',
  },
  {
    id: 16,
    firstName: 'NMat',
    lastName: 'NHardy',
    email: 'nmathardy@gmail.com',
  },
  {
    id: 17,
    firstName: 'PMat',
    lastName: 'PHardy',
    email: 'pmathardy@gmail.com',
  },
];
